{
	header: {
		name: 'Upgrade Advisory tool'
	},
	side_menu_item: [
		{
			link: '/prepareadvisory?start',
			description: 'Start'
		},
		{
			link: '/prepareadvisory?test',
			description: 'Test'
		},
		{
			link: '/prepareadvisory?recreate',
			description: 'Recreate views'
		}
	],
	instruction_points: {
		header: '',
		tagline: '',
		link: ''
	},
	form_comp:{
		header:"Select component",
		ostype: [

            { typeid:1	, lc_value:'Solaris', name:'solaris'},
            { typeid:2	, lc_value:'Solaris x86', name:'solaris'},
            { typeid:3	, lc_value:'Tru64 Unix', name:'trux'},
            { typeid:4	, lc_value:'HP-UX', name:'hpux'},
            { typeid:5	, lc_value:'IBM AIX', name:'aix'},
            { typeid:6	, lc_value:'SunOS', name:'sunos'},
            { typeid:7	, lc_value:'Windows NT', name:'windows'},
            { typeid:8	, lc_value:'Windows', name:'windows'},
            { typeid:9	, lc_value:'IBM OS2', name:'ibmos2'},
            { typeid:10	, lc_value:'Macintosh', name:'macintosh'},
            { typeid:11	, lc_value:'Tandem UNIX', name:'tandemux'},
            { typeid:12	, lc_value:'UNIX Ware', name:'uxware'},
            { typeid:13	, lc_value:'Windows 2000', name:'windows'},
            { typeid:14	, lc_value:'Windows XP', name:'windows'},
            { typeid:15	, lc_value:'Windows Server 2003', name:'windows'},
            { typeid:16	, lc_value:'RedHat Enterprise Linux AS/Intel', name:'linux'},
            { typeid:17	, lc_value:'Windows Server 2008', name:'windows'},
            { typeid:18	, lc_value:'Windows Vista', name:'windows'},
            { typeid:19	, lc_value:'Windows Server 2012', name:'windows'}
			],
		apptype:[
			{"name": ".NET Web API Server and Samples" ,"value":8},
			{"name": "Aastra MXONE CSTA I" ,"value":22},
			{"name": "Administration Console" ,"value":8},
			{"name": "Alcatel A4400/OXE" ,"value":56},
			{"name": "API" ,"value":106},
			{"name": "Aspect ACD" ,"value":24},
			{"name": "Authoring Tool" ,"value":582},
			{"name": "Avaya Communication Manager" ,"value":68},
			{"name": "Avaya TSAPI" ,"value":38},
			{"name": "Backend" ,"value":36},
			{"name": "Builder" ,"value":408},
			{"name": "Business Process for use with Facebook" ,"value":26},
			{"name": "Business Process for use with RSS" ,"value":16},
			{"name": "Business Process for use with Twitter" ,"value":32},
			{"name": "Call Control Platform" ,"value":70},
			{"name": "Call Progress Detection Server" ,"value":8},
			{"name": "CCPulse+" ,"value":20},
			{"name": "Chat Server" ,"value":214},
			{"name": "Cisco Adapter" ,"value":10},
			{"name": "Classification Server" ,"value":136},
			{"name": "CMS" ,"value":184},
			{"name": "Configuration Database Maintenance Scripts" ,"value":56},
			{"name": "Configuration Manager" ,"value":10},
			{"name": "Configuration Server" ,"value":576},
			{"name": "Configuration Utility" ,"value":57},
			{"name": "Contact Center Advisor - Mobile Edition" ,"value":8},
			{"name": "Contact Center Advisor - Mobile Edition Android Client" ,"value":2},
			{"name": "Contact Center Advisor - Mobile Edition Blackberry Client" ,"value":6},
			{"name": "Contact Center Advisor - Mobile Edition iOS Client" ,"value":8},
			{"name": "Contact Center Advisor & Workforce Advisor" ,"value":28},
			{"name": "Content Analyzer Plug-in for GAX" ,"value":6},
			{"name": "CSTA Connector" ,"value":34},
			{"name": "CSTA Connector for BroadSoft BroadWorks" ,"value":32},
			{"name": "CTI Connector" ,"value":174},
			{"name": "Custom Server" ,"value":10},
			{"name": "Daemon" ,"value":92},
			{"name": "Data Aggregator" ,"value":166},
			{"name": "Data Mart" ,"value":4},
			{"name": "Data Modeling Assistant" ,"value":8},
			{"name": "Data Sourcer" ,"value":4},
			{"name": "Database Utility" ,"value":130},
			{"name": "DB Server" ,"value":34},
			{"name": "Development Tool" ,"value":26},
			{"name": "Device Management Plug-in for Genesys Administrator Extension" ,"value":32},
			{"name": "E-mail Server" ,"value":252},
			{"name": "EADS Intecom M6880" ,"value":12},
			{"name": "Engine" ,"value":268},
			{"name": "eServices Manager Plug-in for GAX" ,"value":168},
			{"name": "Fetching Module" ,"value":4},
			{"name": "Frontend" ,"value":36},
			{"name": "Frontline Advisor and Agent Advisor" ,"value":30},
			{"name": "Genesys Adapter" ,"value":26},
			{"name": "Genesys Administrator" ,"value":78},
			{"name": "Genesys Administrator Extension" ,"value":1010},
			{"name": "Genesys Administrator Extension HPE SPD" ,"value":28},
			{"name": "Genesys Agent Scripting" ,"value":40},
			{"name": "Genesys Care Workbench Agent" ,"value":12},
			{"name": "Genesys Care Workbench Log Extractor" ,"value":16},
			{"name": "Genesys Care Workbench Server" ,"value":20},
			{"name": "Genesys Cloud API Driver for  Facebook" ,"value":82},
			{"name": "Genesys Cloud API Driver for  Twitter" ,"value":58},
			{"name": "Genesys Co-browse Server" ,"value":316},
			{"name": "Genesys Data Processing Server" ,"value":40},
			{"name": "Genesys Driver for Use with Facebook" ,"value":198},
			{"name": "Genesys Driver for Use with RSS" ,"value":12},
			{"name": "Genesys Driver for Use with Twitter" ,"value":54},
			{"name": "Genesys Info Mart" ,"value":1150},
			{"name": "Genesys Info Mart Manager" ,"value":44},
			{"name": "Genesys Interactive Insights" ,"value":112},
			{"name": "Genesys Mobile Services" ,"value":966},
			{"name": "Genesys One Base Pack" ,"value":8},
			{"name": "Genesys One Email Pack" ,"value":8},
			{"name": "Genesys One HA Pack" ,"value":4},
			{"name": "Genesys Pulse" ,"value":714},
			{"name": "Genesys Pulse Collector" ,"value":312},
			{"name": "Genesys Quality Management" ,"value":66},
			{"name": "Genesys SIP Voicemail" ,"value":6},
			{"name": "Genesys SIP Voicemail Complete Install" ,"value":8},
			{"name": "Genesys Softphone" ,"value":144},
			{"name": "Genesys SR Service" ,"value":314},
			{"name": "Genesys T-Server and UCMA Connector for Skype for Business" ,"value":360},
			{"name": "Hosted Provider Edition" ,"value":14},
			{"name": "Hosted Provider Edition Agent Desktop Proxy" ,"value":8},
			{"name": "Interaction Recording Web Services" ,"value":140},
			{"name": "Interaction Routing Designer" ,"value":36},
			{"name": "Interaction Server" ,"value":342},
			{"name": "Interaction Server Cluster Plug-in for GAX" ,"value":20},
			{"name": "Interaction Server Proxy" ,"value":124},
			{"name": "Interaction Workflow Samples" ,"value":4},
			{"name": "Interaction Workspace" ,"value":128},
			{"name": "Interaction Workspace Plug-in for Facebook" ,"value":16},
			{"name": "Interaction Workspace Plug-in for Genesys Agent Scripting" ,"value":36},
			{"name": "Interaction Workspace Plug-in for RSS" ,"value":4},
			{"name": "Interaction Workspace Plug-in for Twitter" ,"value":16},
			{"name": "IVR Driver for MPS" ,"value":4},
			{"name": "IVR Driver for WVR for AIX" ,"value":6},
			{"name": "IVR Library" ,"value":4},
			{"name": "IVR SDK" ,"value":4},
			{"name": "IVR Server" ,"value":18},
			{"name": "iWD Data Mart" ,"value":30},
			{"name": "iWD GAX Plug-In" ,"value":132},
			{"name": "iWD Manager" ,"value":258},
			{"name": "iWD Runtime Node" ,"value":204},
			{"name": "iWD Setup Utility" ,"value":6},
			{"name": "iWD Stat Server Extensions" ,"value":46},
			{"name": "iWD Web" ,"value":10},
			{"name": "Java Environment and Libraries for eServices and UCS" ,"value":4},
			{"name": "Knowledge Manager" ,"value":52},
			{"name": "License Reporting Manager" ,"value":18},
			{"name": "Load Distribution Server" ,"value":28},
			{"name": "Local Control Agent" ,"value":176},
			{"name": "Log File Management Tool Client" ,"value":64},
			{"name": "Log File Management Tool Collector" ,"value":16},
			{"name": "Log File Management Tool Indexer" ,"value":16},
			{"name": "Manager" ,"value":6},
			{"name": "Media Control Platform" ,"value":996},
			{"name": "Message Server" ,"value":112},
			{"name": "MIB" ,"value":39},
			{"name": "Mitel MiTAI" ,"value":6},
			{"name": "Mitel MiVoice" ,"value":4},
			{"name": "MRCP Proxy" ,"value":52},
			{"name": "Multi-Channel Routing Extensions" ,"value":2},
			{"name": "NEC NEAX/APEX" ,"value":48},
			{"name": "Nortel Communication Server 1000 with SCCS/MLS" ,"value":32},
			{"name": "Nortel Communication Server 2000/2100" ,"value":26},
			{"name": "Orchestration Server" ,"value":220},
			{"name": "Outbound Contact Center Extension" ,"value":8},
			{"name": "Outbound Contact Server" ,"value":136},
			{"name": "Platform" ,"value":28},
			{"name": "Platform SDK & Application Blocks for .NET" ,"value":42},
			{"name": "Platform SDK & Application Blocks for Java" ,"value":38},
			{"name": "Platform SDK for .NET" ,"value":354},
			{"name": "Platform SDK for Java" ,"value":480},
			{"name": "Plug-in for GAX" ,"value":4},
			{"name": "Plug-in for Genesys Administrator Extension" ,"value":78},
			{"name": "Plug-in for Interaction Workspace" ,"value":42},
			{"name": "Plug-in for Workspace Desktop Edition" ,"value":24},
			{"name": "Plugin for Administrator" ,"value":46},
			{"name": "Plugin for Genesys Administrator Extension" ,"value":74},
			{"name": "Plugin for Workspace Desktop Edition" ,"value":256},
			{"name": "Policy Server" ,"value":14},
			{"name": "Privacy Manager Plugin for GAX" ,"value":40},
			{"name": "PSTN Connector" ,"value":26},
			{"name": "Recording Crypto Server" ,"value":138},
			{"name": "Recording Muxer Script" ,"value":148},
			{"name": "Recording Plug-in for Genesys Administrator Extension" ,"value":164},
			{"name": "Recording Processor Script" ,"value":226},
			{"name": "Reporting and Analytics Aggregates" ,"value":166},
			{"name": "Reporting Dashboard Proxy for Genesys Administrator Extension" ,"value":24},
			{"name": "Reporting Plug-in for GAX" ,"value":6},
			{"name": "Reporting Server" ,"value":242},
			{"name": "Resource Manager" ,"value":544},
			{"name": "Sample Reporting Templates" ,"value":162},
			{"name": "SAP BusinessObjects Business Intelligence Platform Client 3.1.x" ,"value":4},
			{"name": "SAP BusinessObjects Business Intelligence Platform Client 4.1.x" ,"value":6},
			{"name": "SAP BusinessObjects Business Intelligence Platform Client ServicePack 3.1.x" ,"value":4},
			{"name": "SAP BusinessObjects Business Intelligence Platform Client ServicePack 4.1.x" ,"value":4},
			{"name": "SAP BusinessObjects Business Intelligence Platform Server 3.1.x" ,"value":6},
			{"name": "SAP BusinessObjects Business Intelligence Platform Server 4.1.x" ,"value":6},
			{"name": "SAP BusinessObjects Business Intelligence Platform Server Service Pack 3.1.x" ,"value":4},
			{"name": "SAP BusinessObjects Business Intelligence Platform Server ServicePack 4.1.x" ,"value":4},
			{"name": "Security Pack on UNIX" ,"value":120},
			{"name": "Server" ,"value":1212},
			{"name": "Siemens HiPath 4000 CSTA III" ,"value":22},
			{"name": "SIP Endpoint SDK for .NET" ,"value":10},
			{"name": "SIP Endpoint SDK for Apple OS" ,"value":4},
			{"name": "SIP Feature Server" ,"value":110},
			{"name": "SIP Proxy" ,"value":42},
			{"name": "SIP Server" ,"value":452},
			{"name": "sipspan2" ,"value":10},
			{"name": "SMS Server" ,"value":136},
			{"name": "SNMP Master Agent" ,"value":64},
			{"name": "Social Media Plug-in for Workspace Desktop Edition" ,"value":212},
			{"name": "Social Messaging Plugin for Genesys Agent Desktop" ,"value":8},
			{"name": "Social Messaging Server" ,"value":64},
			{"name": "Solution Control Server" ,"value":268},
			{"name": "Spectrum" ,"value":10},
			{"name": "Stat Server" ,"value":914},
			{"name": "Supplementary Services Gateway" ,"value":84},
			{"name": "T-Server Common Part" ,"value":182},
			{"name": "T-Server-CUCM to Media Server Connector" ,"value":26},
			{"name": "Third-Party Squid" ,"value":24},
			{"name": "Training Server" ,"value":36},
			{"name": "UCS Manager" ,"value":10},
			{"name": "Universal Contact Server" ,"value":254},
			{"name": "Universal Contact Server Manager" ,"value":24},
			{"name": "Universal Contact Server Proxy" ,"value":46},
			{"name": "Universal Routing Server" ,"value":116},
			{"name": "VP Reporting Plugin for GAX" ,"value":80},
			{"name": "Web" ,"value":1030},
			{"name": "Web API Server" ,"value":116},
			{"name": "Web API Server for WebLogic" ,"value":6},
			{"name": "Web API Server for WebSphere" ,"value":6},
			{"name": "Web Services and Applications" ,"value":262},
			{"name": "Widgets" ,"value":162},
			{"name": "Workspace Desktop Edition" ,"value":2044},
			{"name": "Workspace Plugin for Skype for Business" ,"value":116}
			]
		},
		form_admin: {
			header: "Choose Database to recreate views",
			databases:[
				{name: "genesys_releases"}
			]
		}


}